FROM docker.elastic.co/elasticsearch/elasticsearch:7.7.0

LABEL maintainer="ermu0420@gmail.com"

COPY ./config/elasticsearch.yml /usr/share/elasticsearch/conifg/elasticsearch.yml

RUN echo "Asia/Shanghai" > /etc/timezone